In [9]:
from dotenv import load_dotenv
import os
import requests
import pandas as pd

In [3]:
load_dotenv()

True

## Trying out API

In [16]:
url = "https://api.themoviedb.org/3/movie/top_rated?language=en-US&page=1"

headers = {
    "accept": "application/json",
    "Authorization": f"Bearer {os.getenv("TMDB_API_READ_ACCESS_TOKEN")}"
}

response = requests.get(url, headers=headers)
results = response.json()["results"]
print(results)

[{'adult': False, 'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg', 'genre_ids': [18, 80], 'id': 278, 'original_language': 'en', 'original_title': 'The Shawshank Redemption', 'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.', 'popularity': 181.683, 'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg', 'release_date': '1994-09-23', 'title': 'The Shawshank Redemption', 'video': False, 'vote_average': 8.708, 'vote_count': 27640}, {'adult': False, 'backdrop_path': '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg', 'genre_ids': [18, 80], 'id': 238, 'original_language': 'en', 'original_title': 'The Godfather', 'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.', 'popularity': 176.205, 'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg', 'release_date': '1972-03-14', 'title': 'The Godfather', 'video': False, 'vote_average': 8.689, 'vote_count': 20959}, {'adult': False, 'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg', 'genre_ids': [18, 80], 'id': 240, 'original_language': 'en', 'original_title': 'The Godfather Part II', 'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.', 'popularity': 99.636, 'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg', 'release_date': '1974-12-20', 'title': 'The Godfather Part II', 'video': False, 'vote_average': 8.57, 'vote_count': 12648}, {'adult': False, 'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg', 'genre_ids': [18, 36, 10752], 'id': 424, 'original_language': 'en', 'original_title': "Schindler's List", 'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.', 'popularity': 108.218, 'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg', 'release_date': '1993-12-15', 'title': "Schindler's List", 'video': False, 'vote_average': 8.567, 'vote_count': 16100}, {'adult': False, 'backdrop_path': '/bxgTSUenZDHNFerQ1whRKplrMKF.jpg', 'genre_ids': [18], 'id': 389, 'original_language': 'en', 'original_title': '12 Angry Men', 'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.", 'popularity': 68.813, 'poster_path': '/ow3wq89wM8qd5X7hWKxiRfsFf9C.jpg', 'release_date': '1957-04-10', 'title': '12 Angry Men', 'video': False, 'vote_average': 8.546, 'vote_count': 8837}, {'adult': False, 'backdrop_path': '/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg', 'genre_ids': [16, 10751, 14], 'id': 129, 'original_language': 'ja', 'original_title': '千と千尋の神隠し', 'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.', 'popularity': 111.481, 'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg', 'release_date': '2001-07-20', 'title': 'Spirited Away', 'video': False, 'vote_average': 8.537, 'vote_count': 16775}, {'adult': False, 'backdrop_path': '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg', 'genre_ids': [35, 18, 10749], 'id': 19404, 'original_language': 'hi', 'original_title': 'दिलवाले दुल्हनिया ले जायेंगे', 'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.', 'popularity': 40.407, 'poster_path': '/lfRkUr7DYdHldAqi3PwdQGBRBPM.jpg', 'release_date': '1995-10-20', 'title': 'Dilwale Dulhania Le Jayenge', 'video': False, 'vote_average': 8.522, 'vote_count': 4456}, {'adult': False, 'backdrop_path': '/plDp52MirFHc2PMJRMNWoG0kfr3.jpg', 'genre_ids': [18, 28, 80, 53], 'id': 155, 'original_language': 'en', 'original_title': 'The Dark Knight', 'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.', 'popularity': 143.293, 'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'release_date': '2008-07-16', 'title': 'The Dark Knight', 'video': False, 'vote_average': 8.519, 'vote_count': 33328}, {'adult': False, 'backdrop_path': '/vxJ08SvwomfKbpboCWynC3uqUg4.jpg', 'genre_ids': [14, 18, 80], 'id': 497, 'original_language': 'en', 'original_title': 'The Green Mile', 'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.", 'popularity': 98.726, 'poster_path': '/o0lO84GI7qrG6XFvtsPOSV7CTNa.jpg', 'release_date': '1999-12-10', 'title': 'The Green Mile', 'video': False, 'vote_average': 8.506, 'vote_count': 17743}, {'adult': False, 'backdrop_path': '/8eihUxjQsJ7WvGySkVMC0EwbPAD.jpg', 'genre_ids': [35, 53, 18], 'id': 496243, 'original_language': 'ko', 'original_title': '기생충', 'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.", 'popularity': 110.996, 'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg', 'release_date': '2019-05-30', 'title': 'Parasite', 'video': False, 'vote_average': 8.5, 'vote_count': 18583}, {'adult': False, 'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg', 'genre_ids': [53, 80], 'id': 680, 'original_language': 'en', 'original_title': 'Pulp Fiction', 'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.", 'popularity': 120.342, 'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg', 'release_date': '1994-09-10', 'title': 'Pulp Fiction', 'video': False, 'vote_average': 8.5, 'vote_count': 28256}, {'adult': False, 'backdrop_path': '/8x9iKH8kWA0zdkgNdpAew7OstYe.jpg', 'genre_ids': [16, 10749, 18], 'id': 372058, 'original_language': 'ja', 'original_title': '君の名は。', 'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.', 'popularity': 84.899, 'poster_path': '/vfJFJPepRKapMd5G2ro7klIRysq.jpg', 'release_date': '2016-08-26', 'title': 'Your Name.', 'video': False, 'vote_average': 8.486, 'vote_count': 11557}, {'adult': False, 'backdrop_path': '/5JrZAtyk3LwiiAWLW0kwz41XZJC.jpg', 'genre_ids': [12, 14, 28], 'id': 122, 'original_language': 'en', 'original_title': 'The Lord of the Rings: The Return of the King', 'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b', 'popularity': 171.817, 'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg', 'release_date': '2003-12-17', 'title': 'The Lord of the Rings: The Return of the King', 'video': False, 'vote_average': 8.483, 'vote_count': 24580}, {'adult': False, 'backdrop_path': '/mzfx54nfDPTUXZOG48u4LaEheDy.jpg', 'genre_ids': [35, 18, 10749], 'id': 13, 'original_language': 'en', 'original_title': 'Forrest Gump', 'overview': 'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', 'popularity': 127.926, 'poster_path': '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg', 'release_date': '1994-06-23', 'title': 'Forrest Gump', 'video': False, 'vote_average': 8.469, 'vote_count': 27784}, {'adult': False, 'backdrop_path': '/x4biAVdPVCghBlsVIzB6NmbghIz.jpg', 'genre_ids': [37], 'id': 429, 'original_language': 'it', 'original_title': 'Il buono, il brutto, il cattivo', 'overview': 'While the Civil War rages on between the Union and the Confederacy, three men – a quiet loner, a ruthless hitman, and a Mexican bandit – comb the American Southwest in search of a strongbox containing $200,000 in stolen gold.', 'popularity': 78.201, 'poster_path': '/bX2xnavhMYjWDoZp1VM6VnU1xwe.jpg', 'release_date': '1966-12-22', 'title': 'The Good, the Bad and the Ugly', 'video': False, 'vote_average': 8.5, 'vote_count': 8774}, {'adult': False, 'backdrop_path': '/sJNNMCc6B7KZIY3LH3JMYJJNH5j.jpg', 'genre_ids': [28, 18], 'id': 346, 'original_language': 'ja', 'original_title': '七人の侍', 'overview': "A samurai answers a village's request for protection after he falls on hard times. The town needs protection from bandits, so the samurai gathers six others to help him teach the people how to defend themselves, and the villagers provide the soldiers with food.", 'popularity': 39.315, 'poster_path': '/iAq0sq42vKTLneVGqHn1D4GzgrM.jpg', 'release_date': '1954-04-26', 'title': 'Seven Samurai', 'video': False, 'vote_average': 8.5, 'vote_count': 3775}, {'adult': False, 'backdrop_path': '/7TF4p86ZafnxFuNqWdhpHXFO244.jpg', 'genre_ids': [18, 80], 'id': 769, 'original_language': 'en', 'original_title': 'GoodFellas', 'overview': 'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.', 'popularity': 80.744, 'poster_path': '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg', 'release_date': '1990-09-12', 'title': 'GoodFellas', 'video': False, 'vote_average': 8.458, 'vote_count': 13067}, {'adult': False, 'backdrop_path': '/dlC0ed9Ugh3FzydnkBtV5lRXUu4.jpg', 'genre_ids': [16, 18, 10752], 'id': 12477, 'original_language': 'ja', 'original_title': '火垂るの墓', 'overview': 'In the final months of World War II, 14-year-old Seita and his sister Setsuko are orphaned when their mother is killed during an air raid in Kobe, Japan. After a falling out with their aunt, they move into an abandoned bomb shelter. With no surviving relatives and their emergency rations depleted, Seita and Setsuko struggle to survive.', 'popularity': 0.077, 'poster_path': '/k9tv1rXZbOhH7eiCk378x61kNQ1.jpg', 'release_date': '1988-04-16', 'title': 'Grave of the Fireflies', 'video': False, 'vote_average': 8.452, 'vote_count': 5683}, {'adult': False, 'backdrop_path': '/vgnoBSVzWAV9sNQUORaDGvDp7wx.jpg', 'genre_ids': [12, 18, 878], 'id': 157336, 'original_language': 'en', 'original_title': 'Interstellar', 'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.', 'popularity': 371.729, 'poster_path': '/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'release_date': '2014-11-05', 'title': 'Interstellar', 'video': False, 'vote_average': 8.45, 'vote_count': 36360}, {'adult': False, 'backdrop_path': '/gavyCu1UaTaTNPsVaGXT6pe5u24.jpg', 'genre_ids': [35, 18], 'id': 637, 'original_language': 'it', 'original_title': 'La vita è bella', 'overview': 'A touching story of an Italian book seller of Jewish ancestry who lives in his own little fairy tale. His creative and happy life would come to an abrupt halt when his entire family is deported to a concentration camp during World War II. While locked up he tries to convince his son that the whole thing is just a game.', 'popularity': 55.887, 'poster_path': '/74hLDKjD5aGYOotO6esUVaeISa2.jpg', 'release_date': '1997-12-20', 'title': 'Life Is Beautiful', 'video': False, 'vote_average': 8.448, 'vote_count': 13162}]

In [20]:
df = pd.DataFrame(results)

df = df.set_index("id")
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 278 to 637
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              20 non-null     bool
 1   backdrop_path      20 non-null     object
 2   genre_ids          20 non-null     object
 3   original_language  20 non-null     object
 4   original_title     20 non-null     object
 5   overview           20 non-null     object
 6   popularity         20 non-null     float64
 7   poster_path        20 non-null     object
 8   release_date       20 non-null     object
 9   title              20 non-null     object
 10  video              20 non-null     bool
 11  vote_average       20 non-null     float64
 12  vote_count         20 non-null     int64
dtypes: bool(2), float64(2), int64(1), object(8)
memory usage: 1.9+ KB

In [26]:
df["poster_path"] = df["poster_path"].map(lambda x: "https://image.tmdb.org/t/p/original"+x)
df["backdrop_path"] = df["backdrop_path"].map(lambda x: "https://image.tmdb.org/t/p/original"+x)
df.head()

,adult,backdrop_path,genre_ids,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
id,,,,,,,,,,,,,
278,False,https://image.tmdb.org/t/p/originalhttps://ima...,"[18, 80]",en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,181.683,https://image.tmdb.org/t/p/originalhttps://ima...,1994-09-23,The Shawshank Redemption,False,8.708,27640
238,False,https://image.tmdb.org/t/p/originalhttps://ima...,"[18, 80]",en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",176.205,https://image.tmdb.org/t/p/originalhttps://ima...,1972-03-14,The Godfather,False,8.689,20959
240,False,https://image.tmdb.org/t/p/originalhttps://ima...,"[18, 80]",en,The Godfather Part II,In the continuing saga of the Corleone crime f...,99.636,https://image.tmdb.org/t/p/originalhttps://ima...,1974-12-20,The Godfather Part II,False,8.570,12648
424,False,https://image.tmdb.org/t/p/originalhttps://ima...,"[18, 36, 10752]",en,Schindler's List,The true story of how businessman Oskar Schind...,108.218,https://image.tmdb.org/t/p/originalhttps://ima...,1993-12-15,Schindler's List,False,8.567,16100
389,False,https://image.tmdb.org/t/p/originalhttps://ima...,[18],en,12 Angry Men,The defense and the prosecution have rested an...,68.813,https://image.tmdb.org/t/p/originalhttps://ima...,1957-04-10,12 Angry Men,False,8.546,8837

## Creating entire dataset

In [27]:
df = pd.DataFrame()

In [28]:
for i in range(1, 497):
    url = f"https://api.themoviedb.org/3/movie/top_rated?language=en-US&page={i}"

    headers = {
        "accept": "application/json",
        "Authorization": f"Bearer {os.getenv("TMDB_API_READ_ACCESS_TOKEN")}"
    }

    response = requests.get(url, headers=headers)
    results = response.json()["results"]

    temp_df = pd.DataFrame(results)
    df = pd.concat([df, temp_df], ignore_index=True)

In [32]:
# df = df.set_index("id")
df["poster_path"] = df["poster_path"].map(lambda x: "https://image.tmdb.org/t/p/original"+x if x else None)
df["backdrop_path"] = df["backdrop_path"].map(lambda x: "https://image.tmdb.org/t/p/original"+x if x else None)

In [33]:
df.shape

(9920, 13)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9920 entries, 278 to 510452
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   adult              9920 non-null   bool
 1   backdrop_path      9909 non-null   object
 2   genre_ids          9920 non-null   object
 3   original_language  9920 non-null   object
 4   original_title     9920 non-null   object
 5   overview           9920 non-null   object
 6   popularity         9920 non-null   float64
 7   poster_path        9913 non-null   object
 8   release_date       9920 non-null   object
 9   title              9920 non-null   object
 10  video              9920 non-null   bool
 11  vote_average       9920 non-null   float64
 12  vote_count         9920 non-null   int64
dtypes: bool(2), float64(2), int64(1), object(8)
memory usage: 949.4+ KB

In [35]:
df.head()

,adult,backdrop_path,genre_ids,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count
id,,,,,,,,,,,,,
278,False,https://image.tmdb.org/t/p/original/zfbjgQE1uS...,"[18, 80]",en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,181.683,https://image.tmdb.org/t/p/original/9cqNxx0GxF...,1994-09-23,The Shawshank Redemption,False,8.708,27640
238,False,https://image.tmdb.org/t/p/original/tmU7GeKVyb...,"[18, 80]",en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",176.205,https://image.tmdb.org/t/p/original/3bhkrj58Vt...,1972-03-14,The Godfather,False,8.689,20959
240,False,https://image.tmdb.org/t/p/original/kGzFbGhp99...,"[18, 80]",en,The Godfather Part II,In the continuing saga of the Corleone crime f...,99.636,https://image.tmdb.org/t/p/original/hek3koDUyR...,1974-12-20,The Godfather Part II,False,8.570,12648
424,False,https://image.tmdb.org/t/p/original/zb6fM1CX41...,"[18, 36, 10752]",en,Schindler's List,The true story of how businessman Oskar Schind...,108.218,https://image.tmdb.org/t/p/original/sF1U4EUQS8...,1993-12-15,Schindler's List,False,8.567,16100
389,False,https://image.tmdb.org/t/p/original/bxgTSUenZD...,[18],en,12 Angry Men,The defense and the prosecution have rested an...,68.813,https://image.tmdb.org/t/p/original/ow3wq89wM8...,1957-04-10,12 Angry Men,False,8.546,8837

In [38]:
df.to_csv("tmdb_top_rated_Mon_Feb_3_16_41_05_IST_2025.csv")